xud-simnet upgrade

diff --git a/scripts/xud-simnet-install b/scripts/xud-simnet-install
--- a/scripts/xud-simnet-install
+++ b/scripts/xud-simnet-install
@@ -86,54 +86,69 @@ make_dir ~/xud-simnet/lndbtc
 make_dir ~/xud-simnet/lndltc
 make_dir ~/xud-simnet/xud-wd
 
-#### glide
-if ! go get -u github.com/Masterminds/glide > /tmp/xud-simnet-install.log 2>&1; then
-	echo "unable to install glide"
-	exit 1
-fi 
-echo "glide installed"
+##### glide
+#if ! go get -u github.com/Masterminds/glide > /tmp/xud-simnet-install.log 2>&1; then
+#	echo "unable to install glide"
+#	exit 1
+#fi 
+#echo "glide installed"
 
 #### ltcd
-if ! git clone https://github.com/offerm/ltcd $GOPATH/src/github.com/ltcsuite/ltcd >> /tmp/xud-simnet-install.log 2>&1; then
+if ! git clone https://github.com/ltcsuite/ltcd.git $GOPATH/src/github.com/ltcsuite/ltcd >> /tmp/xud-simnet-install.log 2>&1; then
 	echo "unable to git clone ltcd"
 	exit 1
 fi
 cd $GOPATH/src/github.com/ltcsuite/ltcd
 echo "ltcd repo downloaded"
-if ! glide install >> /tmp/xud-simnet-install.log 2>&1; then
-	echo "unable to build ltcd"
+if ! git apply ~/xud-simnet/scripts/ltcd.patch >> /tmp/xud-simnet-install.log 2>&1 ; then
+	echo "unable to apply ltcd pacth"
 	exit 1
 fi
-if ! go install . ./cmd/... >> /tmp/xud-simnet-install.log 2>&1; then
+echo "ltcd patched"
+#if ! glide install >> /tmp/xud-simnet-install.log 2>&1; then
+#	echo "unable to build ltcd"
+#	exit 1
+#fi
+if ! GO111MODULE=on go install -v . ./cmd/...  >> /tmp/xud-simnet-install.log 2>&1; then
 	echo "unable to go instll ltcd"
 	exit 1
 fi  
  
 echo "ltcd installed"
 #### btcd
-if ! git clone https://github.com/ExchangeUnion/btcd $GOPATH/src/github.com/btcsuite/btcd >> /tmp/xud-simnet-install.log 2>&1; then
+if ! git clone https://github.com/btcsuite/btcd.git $GOPATH/src/github.com/btcsuite/btcd >> /tmp/xud-simnet-install.log 2>&1; then
 	echo "unable to git clone btcd"
 	exit 1
 fi
 cd $GOPATH/src/github.com/btcsuite/btcd
 echo "btcd repo downloaded"
-if ! glide install >> /tmp/xud-simnet-install.log 2>&1;then
-	echo "unable to build btcd"
+if ! git apply ~/xud-simnet/scripts/btcd.patch >> /tmp/xud-simnet-install.log 2>&1 ; then
+	echo "unable to apply btcd pacth"
 	exit 1
 fi
-if ! go install . ./cmd/... >> /tmp/xud-simnet-install.log 2>&1 ; then
+echo "btcd patched"
+#if ! glide install >> /tmp/xud-simnet-install.log 2>&1;then
+#	echo "unable to build btcd"
+#	exit 1
+#fi
+if ! GO111MODULE=on go install -v . ./cmd/...  >> /tmp/xud-simnet-install.log 2>&1 ; then
 	echo "unable to go instll btcd"
 	exit 1
 fi  
 echo "btcd installed"
 
 #### lnd
-if ! git clone -b v0.6.1-beta-rc2 --depth 1 https://github.com/lightningnetwork/lnd $GOPATH/src/github.com/lightningnetwork/lnd >> /tmp/xud-simnet-install.log 2>&1;then
+if ! git clone -b v0.6.1-beta https://github.com/lightningnetwork/lnd $GOPATH/src/github.com/lightningnetwork/lnd >> /tmp/xud-simnet-install.log 2>&1;then
 	echo "unable to git clone lnd"
 	exit 1
 fi
 cd $GOPATH/src/github.com/lightningnetwork/lnd
 echo "lnd repo downloaded"
+if ! git apply ~/xud-simnet/scripts/limits.patch >> /tmp/xud-simnet-install.log 2>&1 ; then
+	echo "unable to apply lnd limit pacth"
+	exit 1
+fi
+echo "lnd patched"
 if ! GO111MODULE=off GOPATH=$GOPATH make tags="invoicesrpc"  >> /tmp/xud-simnet-install.log 2>&1 ; then
 	echo "unable to make lnd"
 	exit 1
