xud-simnet-check: check existance of utils and PATH

diff --git a/scripts/xud-simnet-check b/scripts/xud-simnet-check
--- a/scripts/xud-simnet-check
+++ b/scripts/xud-simnet-check
@@ -1,5 +1,52 @@
 #!/bin/sh
 
-cd ~/xud-simnet
+# verify existing of ~/xud-simnet
+temp=`ls ~/xud-simnet`
+if [ $? -ne 0 ]; then
+	echo "~/xud-simnet is missing"
+	exit 1
+fi
+# verify git
+temp=`which git`
+if [ $? -ne 0 ]; then
+	echo "git is missing"
+	exit 1
+fi
+# verify make
+temp=`which make`
+if [ $? -ne 0 ]; then
+	echo "make is missing"
+	exit 1
+fi
+# verify npm
+temp=`which npm`
+if [ $? -ne 0 ]; then
+	echo "npm is missing"
+	exit 1
+fi
+# verify killall
+temp=`which killall`
+if [ $? -ne 0 ]; then
+	echo "killall is missing"
+	exit 1
+fi
+# verify go
+temp=`which go`
+if [ $? -ne 0 ]; then
+	echo "go is missing"
+	exit 1
+fi
+# verify PATH
+temp=`echo $PATH|grep xud-simnet/scripts`
+if [ $? -ne 0 ]; then
+	echo "PATH is not properly set. Did you sourced setup.bash?"
+	exit 1
+fi
+# verify PATH
+temp=`echo $PATH|grep xud-simnet/go/bin`
+if [ $? -ne 0 ]; then
+	echo "PATH is not properly set. Did you sourced setup.bash?"
+	exit 1
+fi
 
 echo "looking good!"
