cleanup

diff --git a/scripts/xud-simnet-clean b/scripts/xud-simnet-clean
--- a/scripts/xud-simnet-clean
+++ b/scripts/xud-simnet-clean
@@ -1,8 +1,11 @@
 #!/bin/sh
 
 delete_dir() {
-	rm -rf  $1
-	echo "$1 directory deleted"
+	if ! rm -rf  $1 >/dev/null 2>&1; then
+		echo "unable to delete directory $1"
+		exit 1
+	fi
+	return 0
 }
 
 confirm_not_running() {
@@ -34,5 +37,6 @@ delete_dir "lndltc"
 delete_dir "xud"
 delete_dir "xud-wd"
 delete_dir "go"
+echo "Done. You can now use xud-simnet-install"
 
 
diff --git a/scripts/xud-simnet-install b/scripts/xud-simnet-install
--- a/scripts/xud-simnet-install
+++ b/scripts/xud-simnet-install
@@ -1,41 +1,100 @@
 #!/bin/bash
+make_dir () {
+if ! mkdir "$1"; then
+	echo "$1 already exists. Please run xud-simnet-clear to clean all leftovers before installing."
+	exit 1
+fi
+}
 
-cd ~/xud-simnet
+if ! cd ~/xud-simnet; then
+  	  echo "~/xud-simnet is missing"
+	exit 1
+fi	
 
 source setup.bash
-mkdir ~/xud-simnet/btcd
-mkdir ~/xud-simnet/ltcd
-mkdir ~/xud-simnet/lndbtc
-mkdir ~/xud-simnet/lndltc
-mkdir ~/xud-simnet/xud-wd
+make_dir ~/xud-simnet/btcd
+make_dir ~/xud-simnet/ltcd
+make_dir ~/xud-simnet/lndbtc
+make_dir ~/xud-simnet/lndltc
+make_dir ~/xud-simnet/xud-wd
 
 #### glide
-go get -u github.com/Masterminds/glide 
+if ! go get -u github.com/Masterminds/glide >/dev/null 2>&1; then
+	echo "unable to install glide"
+	exit 1
+fi 
+echo "glide installed"
 
 #### ltcd
-git clone https://github.com/offerm/ltcd $GOPATH/src/github.com/ltcsuite/ltcd
+if ! git clone https://github.com/offerm/ltcd $GOPATH/src/github.com/ltcsuite/ltcd > /dev/null 2>&1; then
+	echo "unable to git clone ltcd"
+	exit 1
+fi
 cd $GOPATH/src/github.com/ltcsuite/ltcd
-glide install
-go install . ./cmd/...  
+echo "ltcd repo downloaded"
+if ! glide install > /dev/null 2>&1; then
+	echo "unable to build ltcd"
+	exit 1
+fi
+if ! go install . ./cmd/... > /dev/null 2>&1; then
+	echo "unable to go instll ltcd"
+	exit 1
+fi  
  
+echo "ltcd installed"
 #### btcd
-git clone https://github.com/btcsuite/btcd $GOPATH/src/github.com/btcsuite/btcd
+if ! git clone https://github.com/btcsuite/btcd $GOPATH/src/github.com/btcsuite/btcd > /dev/null 2>&1; then
+	echo "unable to git clone btcd"
+	exit 1
+fi
 cd $GOPATH/src/github.com/btcsuite/btcd
-glide install
-go install . ./cmd/...  
+echo "ltcd repo downloaded"
+if ! glide install > /dev/null 2>&1;then
+	echo "unable to build btcd"
+	exit 1
+fi
+if ! go install . ./cmd/... > /dev/null 2>&1 ; then
+	echo "unable to go instll ltcd"
+	exit 1
+fi  
+echo "btcd installed"
 
 
 #### lnd
-git clone -b resolver+simnet-ltcd https://github.com/ExchangeUnion/lnd.git $GOPATH/src/github.com/lightningnetwork/lnd
+if ! git clone -b resolver+simnet-ltcd https://github.com/ExchangeUnion/lnd.git $GOPATH/src/github.com/lightningnetwork/lnd > /dev/null 2>&1;then
+	echo "unable to git clone lnd"
+	exit 1
+fi
 cd $GOPATH/src/github.com/lightningnetwork/lnd
-make && make install
+echo "lnd repo downloaded"
+if ! make  > /dev/null 2>&1 ; then
+	echo "unable to make lnd"
+	exit 1
+fi
+echo "lnd compiled"
+if !  make install > /dev/null 2>&1 ; then
+	echo "unable to make install lnd"
+	exit 1
+fi
+echo "lnd installed"
 
 #### xud
 cd ~/xud-simnet
-git clone https://github.com/ExchangeUnion/xud.git
+if ! git clone https://github.com/ExchangeUnion/xud.git > /dev/null 2>&1; then
+	echo "unable to git clone xud"
+	exit 1
+fi
 cd xud
-npm install
-npm run compile
+if ! npm install > /dev/null 2>&1 ; then
+	echo "unable to npm install xud"
+	exit 1
+fi
+if ! npm run compile > /dev/null 2>&1 ; then
+	echo "unable to build xud"
+	exit 1
+fi
+echo "xud installed"
+echo "Ready!"
 
 
 
