raiden scripts

diff --git a/scripts/xud-simnet-install-raiden b/scripts/xud-simnet-install-raiden
--- a/scripts/xud-simnet-install-raiden
+++ b/scripts/xud-simnet-install-raiden
@@ -6,45 +6,35 @@ check_dependencies() {
     echo "python3.7 is missing"
     exit 1
   fi
-#  if ! command -v pip3.7
+#  if ! command -v solc
 #  then
-#    echo "pip3.7 is missing"
-#    exit 1
+#    echo "solc is missing - ignored for now"
+##    exit 1
 #  fi
-#  if ! command -v virtualenv
-#  then
-#    echo "virtualenv is missing"
-#    exit 1
-#  fi
-  if ! command -v solc
-  then
-    echo "solc is missing - ignored for now"
-#    exit 1
-  fi
   echo "found all dependencies for Raiden"
 }
 
-make_dir () {
-if ! mkdir "$1"; then
-	echo "$1 already exists. Please run xud-simnet-clean to clean all leftovers before installing."
-	exit 1
-fi
-}
-
 check_dependencies
+
+cd ~/xud-simnet
+source setup.bash
+make_dir ~/xud-simnet/raiden
+make_dir ~/xud-simnet/raiden-wd
+
 #### raiden
 echo "git clone raiden"
 if ! git clone -b external-secret-resolver-take-two https://github.com/offerm/raiden.git ~/xud-simnet/raiden >> /tmp/xud-simnet-install.log 2>&1; then
 	echo "unable to git clone raiden"
 	exit 1
 fi
-make_dir ~/xud-simnet/raiden-wd
-#virtualenv ~/xud-simnet/raiden-wd/venv
-#cd ~/xud-simnet/raiden-wd || exit 1
-echo "create virtual environment"
-python3.7 -m venv  ~/xud-simnet/raiden-wd/venv
 
-source ~/xud-simnet/raiden-wd/venv/bin/activate
+echo "create virtual environment"
+if ! python3.7 -m venv  ~/xud-simnet/raiden-wd/venv 2>&1;then
+	echo "unable to create virtual env"
+	exit 1
+fi
+
+activate_venv
 
 cd ~/xud-simnet/raiden
 
@@ -65,5 +55,12 @@ if ! python setup.py develop >> /tmp/xud-simnet-install.log 2>&1;then
 	echo "unable to install raiden"
 	exit 1
 fi
+
+echo "123123123" > ~/xud-simnet/raiden-wd/passwd_file
+
+cd ~/xud-simnet/raiden-wd
+python ../scripts/onboarder.py > ~/xud-simnet/raiden-wd/address
+
+deactivate_venv
 
 echo "raiden installed!"
